-- Buatlah design database menggunakan dbdiagram.io dengan entitas objek barangdan kategori barang. Barang dan kategori barang saling berelasi
-- Buatlah query untuk melakukan create table barang dan kategori barang

CREATE TABLE "barang" (
  "id_barang" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_barang" varchar,
  "harga" decimal,
  "stok" integer,
  "id_kategori" integer
);

CREATE TABLE "kategori_barang" (
  "id_kategori" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_katergori" varchar
);

CREATE TABLE "pelanggan" (
  "id_pelanggan" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_pelanggan" varchar,
  "alamat_pelanggan" varchar,
  "nomor_telepon" varchar
);

CREATE TABLE "transaksi" (
  "id_transaksi" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pelanggan" integer,
  "tanggal_transaksi" timestamp DEFAULT 'now'
);

CREATE TABLE "detail_transaksi" (
  "id_detail_transaksi" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_transaksi" integer,
  "id_barang" integer,
  "jumlah_barang" integer,
  "total_harga" integer
);

ALTER TABLE "transaksi" ADD FOREIGN KEY ("id_pelanggan") REFERENCES "pelanggan" ("id_pelanggan");

ALTER TABLE "detail_transaksi" ADD FOREIGN KEY ("id_transaksi") REFERENCES "transaksi" ("id_transaksi");

ALTER TABLE "detail_transaksi" ADD FOREIGN KEY ("id_barang") REFERENCES "barang" ("id_barang");

ALTER TABLE "barang" ADD FOREIGN KEY ("id_kategori") REFERENCES "kategori_barang" ("id_kategori");

-- query tugas

INSERT INTO pelanggan (nama_pelanggan, alamat_pelanggan,nomor_telepon)
	VALUES
		('John Doe','Jl. Contoh No. 123','08123456789'),
		('Jane Smith','Jl. Utama No. 456','08765432123'),
		('Alice Johnson','Jl. Sentral No. 789','08987654321'),
		('Bob Anderson','Jl. Sejati No. 101','08111222333'),
		('Emily Lee','Jl. Bahagia No. 567','08555544433');
		
SELECT * FROM pelanggan;


-- Buatlah query untuk melakukan select, insert, update barang
-- INSERT

INSERT INTO barang(nama_barang, harga, stok, id_kategori)
	VALUES
		('Mainan Robot',500000,100,1),
		('Boneka Beruang',250000,75,2),
		('Lego Kreatif',40000,50,3),
		('Puzzle Edukatif',30000,60,3),
		('Mobil Remote Control',750000,40,1);
		
-- SELECT
		
SELECT * from barang;

-- UPDATE

UPDATE barang SET nama_barang='robot GUNDAM' WHERE id_barang=1;
UPDATE barang SET stok=78 WHERE id_barang=3;


-- Buatlah query untuk melakukan select, insert, update kategori barang
-- INSERT
INSERT INTO kategori_barang(nama_katergori)
	VALUES
		('Mainan Elektronik'),
		('Boneka'),
		('Permainan Edukatif');
		
-- SELECT
SELECT * FROM kategori_barang;

-- UPDATE
UPDATE kategori_barang SET nama_katergori='Boneka Hewan' WHERE id_kategori=2;



-- Buatlah query untuk melakukan join relasi antara barang dan kategori barang
SELECT
	barang.id_barang,
	barang.nama_barang,
	barang.id_kategori,
	kategori_barang.nama_katergori
FROM barang
	INNER JOIN kategori_barang 
		ON barang.id_kategori = kategori_barang.id_kategori;



-- INSERT table transaksi dan detail_transaksi
SELECT * FROM transaksi;

INSERT INTO transaksi(id_pelanggan)
	VALUES
		(1),
		(2),
		(3),
		(1),
		(5),
		(2),
		(4);

INSERT INTO detail_transaksi(id_transaksi, id_barang, jumlah_barang, total_harga)
	VALUES
		(1,1,3,500000 * 3),
		(2,3,1,40000),
		(3,2,2,250000 * 2),
		(1,5,2,750000 * 2),
		(5,4,2,30000 * 2),
		(2,5,1,750000),
		(4,1,5,500000 * 5);
		


-- join table transaksi, detail_transaksi, barang, pelanggan
SELECT 
	detail_transaksi.id_detail_transaksi,
	detail_transaksi.id_transaksi,
	transaksi.id_pelanggan,
	pelanggan.nama_pelanggan,
	barang.nama_barang,
	jumlah_barang,
	total_harga,
	tanggal_transaksi
FROM transaksi
	INNER JOIN detail_transaksi
		ON transaksi.id_transaksi = detail_transaksi.id_transaksi
	INNER JOIN barang
		ON barang.id_barang = detail_transaksi.id_barang
	INNER JOIN pelanggan
		ON	pelanggan.id_pelanggan = transaksi.id_pelanggan;


-- updating id_transaksi pada table detail_transaksi
UPDATE detail_transaksi set id_transaksi=4 where id_detail_transaksi=4;
UPDATE detail_transaksi set id_transaksi=6 where id_detail_transaksi=6;
UPDATE detail_transaksi set id_transaksi=7 where id_detail_transaksi=7;

